site_name: charron.io blog 
site_description: A blogging site about technology, photography, and cooking.
site_url: https://blog.charron.io

extra:
  extra_files:
    - CNAME

theme:
  name: material
  palette:
    # Dark theme
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Light mode
      primary: cyan
      accent: amber
    # Light theme
    - scheme: light
      toggle: 
        icon: material/weather-night
        name: Light mode
      primary: cyan
      accent: amber
  features:
    - content.code.copy

plugins: 
  - search
  - blog:
      blog_dir: .
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      categories_allowed:
        - Cooking
        - Photography
        - Technology
      post_url_format: "{slug}"
  - tags:
      tags_file: tags.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format      

extra_css:
  - stylesheets/extra.css