authors:
  bruce:
    name: Bruce Charron
    description: Me
    #avatar: https://github.com/accounthttps://avatars.githubusercontent.com/u/7622136?v=4
    avatar: images/avatar.png
    url: https://github.com/brucee63 
